### ISSUE TITLE
Request to Showcase my Version !

### ISSUE THREAD

**Issue by hashirshoaeb** [singhkshitij/My-Landing-Page#4]
I have changed the code and create my own version. I will feel glad if you list it in your README.md. Peace. :) 
Here is the link [https://hashirshoaeb.github.io/home/](https://hashirshoaeb.github.io/home/)

**Comment by singhkshitij** [comment]
Hey @hashirshoaeb , Superbly edited.. liked the idea of adding some more details to the page.. Good work.. will surely add it to readme !

**Comment by singhkshitij** [comment]
Done sir (y)

**Comment by hashirshoaeb** [comment]
Thank you sir :)
